package pkg_test

import (
	"context"
	"errors"
	"fmt"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/mock"
	"github.com/stretchr/testify/require"
)

// Repository defines the interface for the data access layer.
// Mocks are generated by mockery v3 via .mockery.yaml config.
type Repository interface {
	Get(ctx context.Context, id string) (*Item, error)
}

// Item represents a domain entity
type Item struct {
	ID   string
	Name string
}

// Service represents the business logic layer
type Service struct {
	repo Repository
}

// NewService creates a new service
func NewService(repo Repository) *Service {
	return &Service{repo: repo}
}

// ProcessItem processes an item
func (s *Service) ProcessItem(ctx context.Context, id string) (*Item, error) {
	// Validate input
	if id == "" {
		return nil, errors.New("id is required")
	}

	// Check for context cancellation before expensive operations
	select {
	case <-ctx.Done():
		return nil, ctx.Err()
	default:
	}

	// Fetch from repository
	item, err := s.repo.Get(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("failed to get item: %w", err)
	}

	// Apply business logic
	if item.Name == "" {
		return nil, errors.New("item name cannot be empty")
	}

	// Add more business logic here
	// e.g., validation, transformation, enrichment

	return item, nil
}

// TestService tests the service layer using mockery v3 generated mocks.
// Mock is generated from Repository interface — no hand-written mocks needed.
func TestService(t *testing.T) {
	tests := []struct {
		name    string
		id      string
		mockFn  func(*MockRepository)
		want    *Item
		wantErr bool
	}{
		{
			name: "success case",
			id:   "123",
			mockFn: func(m *MockRepository) {
				m.EXPECT().Get(mock.Anything, "123").Return(&Item{ID: "123", Name: "test"}, nil).Once()
			},
			want:    &Item{ID: "123", Name: "test"},
			wantErr: false,
		},
		{
			name:    "empty id",
			id:      "",
			mockFn:  func(m *MockRepository) {},
			want:    nil,
			wantErr: true,
		},
		{
			name: "item not found",
			id:   "999",
			mockFn: func(m *MockRepository) {
				m.EXPECT().Get(mock.Anything, "999").Return(nil, ExampleError).Once()
			},
			want:    nil,
			wantErr: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			// Setup — NewMockRepository takes *testing.T for automatic assertion
			mockRepo := NewMockRepository(t)
			tt.mockFn(mockRepo)

			svc := NewService(mockRepo)

			// Execute
			got, err := svc.ProcessItem(context.Background(), tt.id)

			// Assert
			if tt.wantErr {
				require.Error(t, err)
				return
			}
			require.NoError(t, err)
			assert.Equal(t, tt.want, got)
		})
	}
}
