package pkg_test

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"log"
	"os"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/mock"
	"github.com/stretchr/testify/require"
)

// mustGetEnv retrieves an env var or fatals if unset/empty.
// Use for required configuration — fail fast at startup, not at runtime.
func mustGetEnv(key string) string {
	val := os.Getenv(key)
	if val == "" {
		log.Fatalf("required environment variable %s is not set", key)
	}
	return val
}

// mustConnectDB opens a database connection or fatals on failure.
func mustConnectDB(dbURL string) *sql.DB {
	db, err := sql.Open("postgres", dbURL)
	if err != nil {
		log.Fatalf("failed to open database: %v", err)
	}
	if err := db.Ping(); err != nil {
		log.Fatalf("failed to connect to database: %v", err)
	}
	return db
}

// Repository defines the interface for the data access layer.
// Mocks are generated by mockery v3 via .mockery.yaml config.
type Repository interface {
	Get(ctx context.Context, id string) (*Item, error)
	Create(ctx context.Context, item *Item) error
	Update(ctx context.Context, item *Item) error
	WithTx(tx *sql.Tx) Repository
}

// Item represents a domain entity
type Item struct {
	ID   string
	Name string
}

// Service represents the business logic layer
type Service struct {
	db   *sql.DB
	repo Repository
}

// NewService creates a new service.
// All deps are provided by main — no nil checks needed.
func NewService(db *sql.DB, repo Repository) *Service {
	return &Service{db: db, repo: repo}
}

// Example main() wiring:
//
//	func main() {
//	    dbURL := mustGetEnv("DATABASE_URL")
//	    db := mustConnectDB(dbURL)
//	    repo := NewSQLRepository(db)
//	    svc := NewService(db, repo)
//	    handler := NewHandler(svc) // svc satisfies handler's service interface
//	    ...
//	}

// ProcessItem is a non-transactional operation
func (s *Service) ProcessItem(ctx context.Context, id string) (*Item, error) {
	if id == "" {
		return nil, errors.New("id is required")
	}

	select {
	case <-ctx.Done():
		return nil, ctx.Err()
	default:
	}

	item, err := s.repo.Get(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("failed to get item: %w", err)
	}

	if item.Name == "" {
		return nil, errors.New("item name cannot be empty")
	}

	return item, nil
}

// CreateAndUpdate atomically creates one item and updates another.
// Transaction is started here in the service; repo.WithTx scopes it to the transaction.
func (s *Service) CreateAndUpdate(ctx context.Context, newItem *Item, updateID string, updateName string) error {
	tx, err := s.db.BeginTx(ctx, nil)
	if err != nil {
		return fmt.Errorf("begin transaction: %w", err)
	}

	var committed bool
	defer func() {
		if p := recover(); p != nil {
			tx.Rollback()
			panic(p)
		}
		if !committed {
			tx.Rollback()
		}
	}()

	txRepo := s.repo.WithTx(tx)

	if err := txRepo.Create(ctx, newItem); err != nil {
		return fmt.Errorf("create item: %w", err)
	}

	if err := txRepo.Update(ctx, &Item{ID: updateID, Name: updateName}); err != nil {
		return fmt.Errorf("update item: %w", err)
	}

	if err := tx.Commit(); err != nil {
		return fmt.Errorf("commit transaction: %w", err)
	}
	committed = true

	return nil
}

// TestService_ProcessItem tests the service layer using mockery v3 generated mocks.
// Mock is generated from Repository interface — no hand-written mocks needed.
func TestService_ProcessItem(t *testing.T) {
	tests := []struct {
		name    string
		id      string
		mockFn  func(*MockRepository)
		want    *Item
		wantErr bool
	}{
		{
			name: "success case",
			id:   "123",
			mockFn: func(m *MockRepository) {
				m.EXPECT().Get(mock.Anything, "123").Return(&Item{ID: "123", Name: "test"}, nil).Once()
			},
			want:    &Item{ID: "123", Name: "test"},
			wantErr: false,
		},
		{
			name:    "empty id",
			id:      "",
			mockFn:  func(m *MockRepository) {},
			want:    nil,
			wantErr: true,
		},
		{
			name: "item not found",
			id:   "999",
			mockFn: func(m *MockRepository) {
				m.EXPECT().Get(mock.Anything, "999").Return(nil, ExampleError).Once()
			},
			want:    nil,
			wantErr: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			// Setup — NewMockRepository takes *testing.T for automatic assertion
			mockRepo := NewMockRepository(t)
			tt.mockFn(mockRepo)

			db, dbMock, err := sqlmock.New()
			require.NoError(t, err)
			defer db.Close()
			dbMock.ExpectationsWereMet() // no queries expected for this test

			svc := NewService(db, mockRepo)

			got, err := svc.ProcessItem(context.Background(), tt.id)

			if tt.wantErr {
				require.Error(t, err)
				return
			}
			require.NoError(t, err)
			assert.Equal(t, tt.want, got)
		})
	}
}

// TestService_CreateAndUpdate tests the transactional method using sqlmock.
// The mock repo's WithTx returns itself so all calls are captured on the same mock.
func TestService_CreateAndUpdate(t *testing.T) {
	tests := []struct {
		name       string
		newItem    *Item
		updateID   string
		updateName string
		mockFn     func(*MockRepository, sqlmock.Sqlmock)
		wantErr    bool
	}{
		{
			name:       "success case",
			newItem:    &Item{ID: "new", Name: "new item"},
			updateID:   "existing",
			updateName: "updated name",
			mockFn: func(m *MockRepository, dbMock sqlmock.Sqlmock) {
				dbMock.ExpectBegin()
				m.EXPECT().WithTx(mock.Anything).Return(m).Once()
				m.EXPECT().Create(mock.Anything, &Item{ID: "new", Name: "new item"}).Return(nil).Once()
				m.EXPECT().Update(mock.Anything, &Item{ID: "existing", Name: "updated name"}).Return(nil).Once()
				dbMock.ExpectCommit()
			},
			wantErr: false,
		},
		{
			name:       "create fails — transaction rolls back",
			newItem:    &Item{ID: "new", Name: "new item"},
			updateID:   "existing",
			updateName: "updated name",
			mockFn: func(m *MockRepository, dbMock sqlmock.Sqlmock) {
				dbMock.ExpectBegin()
				m.EXPECT().WithTx(mock.Anything).Return(m).Once()
				m.EXPECT().Create(mock.Anything, mock.Anything).Return(ExampleError).Once()
				dbMock.ExpectRollback()
			},
			wantErr: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			db, dbMock, err := sqlmock.New()
			require.NoError(t, err)
			defer db.Close()

			mockRepo := NewMockRepository(t)
			tt.mockFn(mockRepo, dbMock)

			svc := NewService(db, mockRepo)

			err = svc.CreateAndUpdate(context.Background(), tt.newItem, tt.updateID, tt.updateName)

			if tt.wantErr {
				require.Error(t, err)
			} else {
				require.NoError(t, err)
			}

			require.NoError(t, dbMock.ExpectationsWereMet())
		})
	}
}
